name: Laravel

on:
  push:
    branches: ["main", "test"]
  pull_request:
    branches: ["main", "test"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy .env
        run: cp .env.example .env
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3.1"
      - name: Install Dependencies
        run: composer update --no-interaction --no-progress --prefer-dist --optimize-autoloader --no-scripts --no-dev --ignore-platform-reqs -W
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: php artisan migrate --seed
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: laravel
          DB_PASSWORD: secret
        run: vendor/bin/phpunit
